services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://backend:${BACKEND_PORT:-5070}/rpc}"
    ports:
      - "${FRONTEND_PORT:-5080}:3000"
    depends_on:
      - backend
    restart: always

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
    environment:
      - PORT=${BACKEND_PORT:-5070}
    restart: always

  # backend-db:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: meter-lab
  #   volumes:
  #     - backend-db-data:/var/lib/postgresql/data

  # auth:
  #   build: ./apps/auth
  #   ports:
  #     - 3002:3002

  # auth-db:
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: meter-lab
  #   volumes:
  #     - auth-db-data:/var/lib/postgresql/data

volumes:
  backend-db-data:
  auth-db-data:
