services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_PORT:-5070}}"
        PUBLIC_AUTH_URL: "${PUBLIC_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}"
    ports:
      - "${WEB_PORT:-5080}:${WEB_PORT:-5080}"
    depends_on:
      - backend
      - auth
    restart: always
    networks:
      - meter-lab

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
    environment:
      PORT: ${BACKEND_PORT:-5070}
    restart: always
    networks:
      - meter-lab
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # backend-db:
  #   image: postgres:latest
  #   ports:
  #     - "${BACKEND_DB_PORT:-5432}:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: meter-lab
  #   volumes:
  #     - backend-db-data:/var/lib/postgresql

  auth:
    image: auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "${AUTH_PORT:-5090}:${AUTH_PORT:-5090}"
    environment:
      PORT: ${AUTH_PORT:-5090}
      DATABASE_URL: postgres://postgres:postgres@auth-db:5432/auth
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secret}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
    depends_on:
      - auth-db
    restart: always
    networks:
      - meter-lab

  auth-db:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - meter-lab

networks:
  meter-lab:
    driver: bridge

volumes:
  backend-db-data:
  auth-db-data:
