services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_PORT:-5070}}"
        PUBLIC_AUTH_URL: "${PUBLIC_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}"
        PUBLIC_WEBSOCKET_URL: "${PUBLIC_WEBSOCKET_URL:-ws://localhost:${WEBSOCKET_PORT:-5071}}"
    ports:
      - "${WEB_PORT:-5080}:${WEB_PORT:-5080}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - auth
    restart: unless-stopped
    networks:
      - meter-lab

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
      - "${WEBSOCKET_PORT:-5071}:${WEBSOCKET_PORT:-5071}"
    environment:
      PORT: ${BACKEND_PORT:-5070}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT:-5071}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DATABASE_URL: postgres://postgres:postgres@backend-db:5432/meter-lab
      EMQX_URL: ${EMQX_URL:-mqtt://host.docker.internal:1884}
      EMQX_TOPIC: ${EMQX_TOPIC:-mock-data}
      EMQX_USERNAME: ${EMQX_USERNAME:-admin}
      EMQX_PASSWORD: ${EMQX_PASSWORD:-admin123}
      NODE_ENV: ${NODE_ENV:-development}
    restart: unless-stopped
    depends_on:
      - backend-db
    networks:
      - meter-lab

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - meter-lab

  backend-db:
    image: postgres:latest
    ports:
      - "${BACKEND_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${BACKEND_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${BACKEND_DB_NAME:-meter-lab}
    restart: unless-stopped
    volumes:
      - backend-db-data:/var/lib/postgresql
    networks:
      - meter-lab

  auth:
    image: auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "${AUTH_PORT:-5090}:${AUTH_PORT:-5090}"
    environment:
      PORT: ${AUTH_PORT:-5090}
      HOST: "0.0.0.0"
      DATABASE_URL: postgres://postgres:postgres@auth-db:5432/auth
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secretsome-secretsome-secretsome-secretsome-secretsome-secret}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
    depends_on:
      - auth-db
    restart: unless-stopped
    networks:
      - meter-lab

  auth-db:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth}
    restart: unless-stopped
    volumes:
      - auth-db-data:/var/lib/postgresql
    networks:
      - meter-lab

networks:
  meter-lab:
    driver: bridge

volumes:
  backend-db-data:
  auth-db-data:
