services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_PORT:-5070}}"
        PUBLIC_AUTH_URL: "${PUBLIC_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}"
    ports:
      - "${WEB_PORT:-5080}:${WEB_PORT:-5080}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      # - auth
    restart: always
    networks:
      - meter-lab

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
    environment:
      PORT: ${BACKEND_PORT:-5070}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT:-5071}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-next:5090}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DATABASE_URL: postgres://postgres:postgres@backend-db:5432/meter-lab
      EMQX_URL: ${EMQX_URL:-http://host.docker.internal:1883}
      EMQX_TOPIC: ${EMQX_TOPIC:-meter-lab/data}
      EMQX_USERNAME: ${EMQX_USERNAME:-admin}
      EMQX_PASSWORD: ${EMQX_PASSWORD:-admin123}
      NODE_ENV: ${NODE_ENV:-development}
      BACKEND_RUN_MIGRATIONS: ${BACKEND_RUN_MIGRATIONS:-false}
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - meter-lab

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - meter-lab

  backend-db:
    image: postgres:latest
    ports:
      - "${BACKEND_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${BACKEND_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${BACKEND_DB_NAME:-meter-lab}
    volumes:
      - backend-db-data:/var/lib/postgresql
    networks:
      - meter-lab

  # auth:
  #   image: auth:latest
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #   ports:
  #     - "${AUTH_PORT:-5090}:${AUTH_PORT:-5090}"
  #   environment:
  #     PORT: ${AUTH_PORT:-5090}
  #     HOST: "0.0.0.0"
  #     DATABASE_URL: postgres://postgres:postgres@auth-db:5432/auth
  #     BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secret}
  #     BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
  #     ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
  #     ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme123}
  #     ADMIN_NAME: ${ADMIN_NAME:-Admin User}
  #   depends_on:
  #     - auth-db
  #   restart: always
  #   networks:
  #     - meter-lab

  auth-next:
    image: auth-next:latest
    build:
      context: .
      dockerfile: ./apps/auth-next/Dockerfile
    ports:
      - "${AUTH_PORT:-5090}:${AUTH_PORT:-5090}"
    environment:
      PORT: ${AUTH_PORT:-5090}
      HOST: "0.0.0.0"
      DATABASE_HOST: ${AUTH_DB_HOST:-auth-db}
      DATABASE_PORT: ${AUTH_DB_PORT:-5432}
      DATABASE_USER: ${AUTH_DB_USER:-postgres}
      DATABASE_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      DATABASE_NAME: ${AUTH_DB_NAME:-auth}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secret}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme123}
      ADMIN_NAME: ${ADMIN_NAME:-Admin User}
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: always
    networks:
      - meter-lab

  auth-db:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth}
    volumes:
      - auth-db-data:/var/lib/postgresql
    networks:
      - meter-lab

  migrate:
    image: migrate:latest
    build:
      context: .
      dockerfile: ./packages/migrate/Dockerfile
    environment:
      BACKEND_DATABASE_URL: postgres://${BACKEND_DB_USER:-postgres}:${BACKEND_DB_PASSWORD:-postgres}@backend-db:5432/${BACKEND_DB_NAME:-meter-lab}
      AUTH_NEXT_DATABASE_HOST: ${AUTH_DB_HOST:-auth-db}
      AUTH_NEXT_DATABASE_PORT: ${AUTH_DB_PORT:-5432}
      AUTH_NEXT_DATABASE_USER: ${AUTH_DB_USER:-postgres}
      AUTH_NEXT_DATABASE_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      AUTH_NEXT_DATABASE_NAME: ${AUTH_DB_NAME:-auth}
      AUTH_DATABASE_URL: postgres://${AUTH_DB_USER:-postgres}:${AUTH_DB_PASSWORD:-postgres}@auth-db:5432/${AUTH_DB_NAME:-auth}
    depends_on:
      - backend-db
      - auth-db
    restart: "no"
    networks:
      - meter-lab

networks:
  meter-lab:
    driver: bridge

volumes:
  backend-db-data:
  auth-db-data:
