services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_PORT:-5070}}"
    ports:
      - "${FRONTEND_PORT:-5080}:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - meter-lab

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
    environment:
      - PORT=${BACKEND_PORT:-5070}
    restart: unless-stopped
    networks:
      - meter-lab

  # backend-db:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: meter-lab
  #   volumes:
  #     - backend-db-data:/var/lib/postgresql/data

  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #   ports:
  #     - "${AUTH_PORT:-5060}:3000"
  #   environment:
  #     PORT: 3000
  #     DATABASE_URL: postgres://postgres:postgres@auth-db:5432/auth
  #     BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-secret}
  #     BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5060}}
  #   depends_on:
  #     - auth-db

  auth-db:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth}
    volumes:
      - auth-db-data:/var/lib/postgresql/data

networks:
  meter-lab:
    driver: bridge

volumes:
  backend-db-data:
  auth-db-data:
