services:
  # If you change the image name, you need to change it in the deployment workflow as well
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_PORT:-5070}}"
        PUBLIC_AUTH_URL: "${PUBLIC_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}"
        ENVIROMENT: ${ENVIROMENT:-prod}
    ports:
      - "${WEB_PORT:-5080}:${WEB_PORT:-5080}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - auth
    restart: unless-stopped
    networks:
      - meter-lab

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5070}:${BACKEND_PORT:-5070}"
    environment:
      PORT: ${BACKEND_PORT:-5070}
      BACKEND_RUN_MIGRATIONS: ${BACKEND_RUN_MIGRATIONS:-false}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth:5090}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DATABASE_HOST: ${BACKEND_DB_HOST:-backend-db}
      DATABASE_PORT: ${BACKEND_DB_PORT:-5432}
      DATABASE_USER: ${BACKEND_DB_USER:-postgres}
      DATABASE_PASSWORD: ${BACKEND_DB_PASSWORD:-postgres}
      DATABASE_NAME: ${BACKEND_DB_NAME:-meter-lab}
      EMQX_URL: ${EMQX_URL:-mqtt://host.docker.internal:1884}
      EMQX_TOPIC: ${EMQX_TOPIC:-mock-data}
      EMQX_USERNAME: ${EMQX_USERNAME:-admin}
      EMQX_PASSWORD: ${EMQX_PASSWORD:-admin123}
      NODE_ENV: ${NODE_ENV:-development}
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - meter-lab

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - meter-lab

  backend-db:
    image: postgres:latest
    ports:
      - "${BACKEND_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${BACKEND_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${BACKEND_DB_NAME:-meter-lab}
    restart: unless-stopped
    volumes:
      - backend-db-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${BACKEND_DB_USER:-postgres} -d ${BACKEND_DB_NAME:-meter-lab}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - meter-lab

  auth:
    image: auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      args:
        DATABASE_HOST: ${AUTH_DB_HOST:-auth-db}
        DATABASE_PORT: ${AUTH_DB_PORT:-5432}
        DATABASE_USER: ${AUTH_DB_USER:-postgres}
        DATABASE_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
        DATABASE_NAME: ${AUTH_DB_NAME:-auth}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secret}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
        ENVIROMENT: ${ENVIROMENT:-prod}
    ports:
      - "${AUTH_PORT:-5090}:${AUTH_PORT:-5090}"
    environment:
      PORT: ${AUTH_PORT:-5090}
      HOST: "0.0.0.0"
      DATABASE_HOST: ${AUTH_DB_HOST:-auth-db}
      DATABASE_PORT: ${AUTH_DB_PORT:-5432}
      DATABASE_USER: ${AUTH_DB_USER:-postgres}
      DATABASE_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      DATABASE_NAME: ${AUTH_DB_NAME:-auth}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-some-secret}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:${AUTH_PORT:-5090}}
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - meter-lab

  auth-db:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PUBLIC_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_DB_NAME:-auth}
    restart: unless-stopped
    volumes:
      - auth-db-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_DB_USER:-postgres} -d ${AUTH_DB_NAME:-auth}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - meter-lab

  migrate:
    image: migrate:latest
    build:
      context: .
      dockerfile: ./packages/migrate/Dockerfile
    environment:
      BACKEND_DATABASE_HOST: ${BACKEND_DB_HOST:-backend-db}
      BACKEND_DATABASE_PORT: ${BACKEND_DB_PORT:-5432}
      BACKEND_DATABASE_USER: ${BACKEND_DB_USER:-postgres}
      BACKEND_DATABASE_PASSWORD: ${BACKEND_DB_PASSWORD:-postgres}
      BACKEND_DATABASE_NAME: ${BACKEND_DB_NAME:-meter-lab}
      AUTH_DATABASE_HOST: ${AUTH_DB_HOST:-auth-db}
      AUTH_DATABASE_PORT: ${AUTH_DB_PORT:-5432}
      AUTH_DATABASE_USER: ${AUTH_DB_USER:-postgres}
      AUTH_DATABASE_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
      AUTH_DATABASE_NAME: ${AUTH_DB_NAME:-auth}
    depends_on:
      backend-db:
        condition: service_healthy
      auth-db:
        condition: service_healthy
    restart: "no"
    networks:
      - meter-lab

networks:
  meter-lab:
    driver: bridge

volumes:
  backend-db-data:
  auth-db-data:
