apiVersion: v1
kind: Service
metadata:
  name: meter-lab-backend-service
  labels:
    app: meter-lab
spec:
  type: ClusterIP
  selector:
    io.kompose.service: backend
  ports:
  - name: http
    port: 80
    targetPort: 5070
    protocol: TCP