apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meter-lab-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: meter-lab-ingress-ip
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: gce
  tls:
  - hosts:
    - nordicode.se
    - auth.nordicode.se
    - api.nordicode.se
    secretName: nordicode-tls
  rules:
  - host: nordicode.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meter-lab-web-service
            port:
              number: 80
  - host: auth.nordicode.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meter-lab-auth-service
            port:
              number: 80
  - host: api.nordicode.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meter-lab-backend-service
            port:
              number: 80
