apiVersion: v1
kind: Service
metadata:
  name: meter-lab-web-loadbalancer
  labels:
    app: meter-lab
spec:
  type: ClusterIP
  selector:
    io.kompose.service: web
  ports:
  - name: http
    port: 80
    targetPort: 5080
    protocol: TCP