apiVersion: v1
kind: Service
metadata:
  name: meter-lab-backend-websocket-loadbalancer
  labels:
    app: meter-lab
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: websocket
  ports:
  - name: http
    port: 80
    targetPort: 5071
    protocol: TCP