apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: meter-lab
spec:
  type: ClusterIP
  selector:
    app: websocket
  ports:
  - name: http
    port: 80
    targetPort: 5071
    protocol: TCP
