apiVersion: v1
kind: Service
metadata:
  name: meter-lab-loadbalancer
  labels:
    app: meter-lab
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: web
  ports:
  - name: http
    port: 5070
    targetPort: 5070
    protocol: TCP
